default:
  theme : "advanced"
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: "none"
  theme_advanced_path : false
  theme_advanced_buttons1 : "bold,italic,underline|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontsizeselect,|,cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,forecolor"
  theme_advanced_buttons2 : "link,unlink,|,tablecontrols"
  theme_advanced_resizing : true
  force_p_newlines : false
  force_br_newlines : false
  forced_root_block : false
  convert_newlines_to_brs: false
  remove_linebreaks : true
  plugins:
    - table
    - spellchecker
    - autolink
  skin: "o2k7"
  skin_variant : "silver"

ipad:
  theme : "advanced"
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: "none"
  theme_advanced_path : false
  theme_advanced_buttons1 : "bold,italic,underline|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontsizeselect,|,cut,copy,paste"
  theme_advanced_buttons2 : "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,forecolor,|,link,unlink,|,tablecontrols"
  theme_advanced_resizing : true
  force_p_newlines : false
  force_br_newlines : false
  forced_root_block : false
  convert_newlines_to_brs: false
  remove_linebreaks : true
  plugins:
    - table
    - spellchecker
    - autolink
  skin: "o2k7"
  skin_variant : "silver"
